version: '3'
services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guac_admin
      POSTGRES_PASSWORD: CompNet2486
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - guacnet
  guacd:
    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - guacnet
  guac-server-1:
    image: guacamole/guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_ENABLED: "true"
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guac_admin
      POSTGRESQL_PASSWORD: CompNet2486
      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd
    networks:
      - guacnet

  guac-server-2:
    image: guacamole/guacamole
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      POSTGRESQL_ENABLED: "true"
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USERNAME: guac_admin
      POSTGRESQL_PASSWORD: CompNet2486

      GUACD_HOSTNAME: guacd
    depends_on:
      - postgres
      - guacd
    networks:
      - guacnet
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - guac-server-1
      - guac-server-2
    networks:
      - guacnet
volumes:
  postgres_data:
networks:
  guacnet:
  

